### PR TITLE
Bs 12 product view home page

### PR DESCRIPTION
**Pull request by dantvi**
**HTML:**
- Container for dynamically rendered book cards.

**CSS:**
- Styling for the book cards, including hover effects and a responsive layout using Flexbox.

**JavaScript:**
- Fetching book data from the backend API.
- Dynamically creating and rendering book cards with data (title, author, price, and cover image).
- Error handling for failed API requests.

### CODE REVIEW

**Review by sarahosterhed — APPROVED** [review]
Ser bra ut! 👏🏻

**Review by mjp414 — COMMENTED** [review]
Code looks good, however there seems to be a merge conflict in html and css. Might just need to update and fetch from remote in case there's been some changes? 
Otherwise it seems fine!

**Comment by dantvi** [comment]
> Code looks good, however there seems to be a merge conflict in html and css. Might just need to update and fetch from remote in case there's been some changes? Otherwise it seems fine!

Thanks for pointing that out 😊 The merge conflicts in both the HTML and CSS files have now been resolved. I've updated and fetched the latest changes from the remote repository to ensure everything is up-to-date. Let me know if there's anything else you'd like me to adjust!

**Review by mjp414 — APPROVED** [review]
Looks great! 👍

**Pull request merged**
